name: On release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_rocm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU and Buildx
        id: setup
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfile.rocm-builder
          push: true
          platforms: linux/amd64
          tags: rocm
          cache-from: type=registry,ref=rocm
  release_onnx:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU and Buildx
        id: setup
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker buildx build --no-cache --platform linux/amd64 -f build/Dockerfile.onnxruntime --output type=local,dest=out/ .
          for filename in out/**/*.tar.gz out/**/*.whl; do
            [ -e "$filename" ] || continue
            gh release upload ${{github.event.release.tag_name}} "$filename"
          done
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
